name: GitHub Actions Demo On The Playground
on: 
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
    workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
              service_account_email: ${{ secrets.GCP_SA_EMAIL }}
              service_account_key: ${{ secrets.GCP_SA_KEY }}
              project_id: ${{ secrets.GCP_PROJECT_ID }}
              export_default_credentials: true 
      - name: deploy the python function
        run: gcloud functions deploy helloworld --trigger-http --runtime=python39
