name: Github Actions Playground POC

on:
  push:
    branches: [ master ]
    paths:
      - "rex/universal-rocketeer-directory/pto/**"
  pull_request:
    branches: [ master ]
    paths:
      - "rex/universal-rocketeer-directory/pto/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Serverless Framework
        run: npm i -g serverless
        
      - name: Install project dependencies
        run: | 
          cd ./rex/universal-rocketeer-directory/pto
          npm i

      - name: Configure GCP Auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.process_286_serverless }}
          service_account: "serverless@it-urd.iam.gserviceaccount.com"

      - name: Deploy to GCF
        run: |
          cd ./rex/universal-rocketeer-directory/pto
          cat >> credentials.json << EOF
          ${{ secrets.process_286_serverless }}
          EOF
          sls deploy