name: Github Actions Playground POC

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Serverless Framework
        run: npm i -g serverless
      
      - name: Install GCP Cloud Functions Serverless Plug-In
        run: serverless plugin install -n serverless-google-cloudfunctions

      - name: Configure GCP Auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY}} # credentials are inside Github Actions Settings
          service_account: ${{secrets.GCP_SA_EMAIL}}

      - name: Deploy to GCF
        run: |
          cd .
          cat >> credentials.json << EOF
          ${{ secrets.GCP_SA_KEY }}
          EOF
          sls deploy