#TODO: Serverless Composite Specific Path
#TODO: Only Build/Deploy if files other than specific was changed
#TODO: Setup Github Actions Environment Secrets.

name: Github Actions Playground POC

on:
  workflow_dispatch:

jobs:
  deploy-production:
    environment: Production
    name: Deploy Production (Master)
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/master' # this deploys to different projects since it is production
      steps:
        - uses: actions/checkout@v3

        - name: Install Serverless Framework
          run: npm i -g serverless
        
        - name: Install GCP Cloud Functions Serverless Plug-In
          run: serverless plugin install -n serverless-google-cloudfunctions

        - name: Configure GCP Auth
          uses: google-github-actions/auth@v0.7.3
          with:
            credentials_json: ${{secrets.GCP_SA_KEY}} # credentials are inside Github Actions Settings
            service_account: ${{secrets.GCP_SA_EMAIL}}

        - name: Deploy to GCF
          run: |
            cd .
            cat >> credentials.json << EOF
            ${{ secrets.GCP_SA_KEY }}
            EOF
            sls deploy

  deploy-staging:
    environment: Staging
    name: Deploy Staging (Develop)
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/develop' # this deploys both to production since they are in staging.
      steps:
        - uses: actions/checkout@v3

        - name: Install Serverless Framework
          run: npm i -g serverless
        
        - name: Install GCP Cloud Functions Serverless Plug-In
          run: serverless plugin install -n serverless-google-cloudfunctions

        - name: Configure GCP Auth
          uses: google-github-actions/auth@v0.7.3
          with:
            credentials_json: ${{secrets.GCP_SA_KEY}} # credentials are inside Github Actions Settings
            service_account: ${{secrets.GCP_SA_EMAIL}}

        - name: Deploy to GCF
          run: |
            cd .
            cat >> credentials.json << EOF
            ${{ secrets.GCP_SA_KEY }}
            EOF
            sls deploy