# TODO: Deploy only if conditions are met
# Multi-Stage Deployments are inside the Github Action settings

name: GitHub Actions Demo On The Playground
on: 
    # push:
    #   branches: [ main ]
    # pull_request:
    #   branches: [ main ]
    workflow_dispatch:
    
jobs:
  deploy-staging:
    name: Deploy to staging
    environment:
      name: Staging Environment # can set the environment here
    runs-on: ubuntu-latest
    steps:
      - name: deploy to staging environment
        working-directory: bye # certain deployment for certain folder
      - name: Serverless
        uses: serverless/github-action@v1.53.0
        with:
         args: deploy
        env:
         SERVERLESS_ACCESS_KEY: ${{secrets.SERVERLESS_ACCESS_KEY}}
